version: '3'
services:
  server:
    build:
      context: ./backend
    ports:
      - "3000:3000"
  
  client:
    build:
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - server

